# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: OAGILAB
description: >- # this means to ignore newlines until "baseurl:"
  Observational Artificial General Intelligence Lab - Fixing 
  Healthcare One Bit and a Qbit at the time.
twitter_username: oagilab
github_username: oagilab
minimal_mistakes_skin: air
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:French Theoretical Physicist
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/Minimal Mistakes remotePost Formats theme starter

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Karim Metallaoui"
  avatar : "/assets/images/profile.webp"
  bio    : "French Theoretical Physicist - Computational Scientist and Founder"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://oagilab.org"
    - label: "Twitter"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://x.com/oagilab"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/oagilab"   

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://x.com/oagilab"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/oagilab"   

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
